#!/usr/bin/env python                                                                                                                                                                                                              
# -*- coding: utf-8 -*-                                                                                                                                                                                                            
#                                                                                                                                                                                                                                  
# Copyright (c) 2018 Michael Edie / @c0demech                                                                                                                                                                                      
#                                                                                                                                                                                                                                  
# Permission is hereby granted, free of charge, to any person obtaining a copy                                                                                                                                                     
# of this software and associated documentation files (the "Software"), to deal                                                                                                                                                    
# in the Software without restriction, including without limitation the rights                                                                                                                                                     
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell                                                                                                                                                        
# copies of the Software, and to permit persons to whom the Software is                                                                                                                                                            
# furnished to do so, subject to the following conditions:                                                                                                                                                                         
#                                                                                                                                                                                                                                  
# The above copyright notice and this permission notice shall be included in                                                                                                                                                       
# all copies or substantial portions of the Software.                                                                                                                                                                              
#                                                                                                                                                                                                                                  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR                                                                                                                                                       
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,                                                                                                                                                         
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE                                                                                                                                                      
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER                                                                                                                                                           
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,                                                                                                                                                    
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN                                                                                                                                                        
# THE SOFTWARE.                                                                                                                                                                                                                    
import re                                                                                                                                                                                                                          
import sys                                                                                                                                                                                                                         
#                                                                                                                                                                                                                                  
# objdump -D file | ./obj2shell.py                                                                                                                                                                                                 
#                                                                                                                                                                                                                                  
__email__ = "michael@sawbox.net"                                                                                                                                                                                                   
__description__ = "Parses objdump(1) input and converts it to shellcode"                                                                                                                                                           
                                                                                                                                                                                                                                   
opcode = re.compile(r"(^[0-9a-f]{2}$)")                                                                                                                                                                                            
hexlist = []                                                                                                                                                                                                                       
                                                                                                                                                                                                                                   
def main():                                                                                                                                                                                                                        
  for line in sys.stdin:                                                                                                                                                                                                           
    for n in line.split():                                                                                                                                                                                                         
      match = opcode.findall(n)                                                                                                                                                                                                    
      if match:                                                                                                                                                                                                                    
        hexlist.append(match[0])                                                                                                                                                                                                   
  print "Shellcode: %s bytes" % len(hexlist)                                                                                                                                                                                       
  print("%s" % format_opcodes(hexlist))                                                                                                                                                                                            
                                                                                                                                                                                                                                   
def format_opcodes(hexchars):                                                                                                                                                                                                      
  shellcode = ""                                                                                                                                                                                                                   
  for x in hexchars:                                                                                                                                                                                                               
    shellcode += "\\x" + x                                                                                                                                                                                                         
  return shellcode                                                                                                                                                                                                                 
                                                                                                                                                                                                                                   
if __name__ == '__main__':                                                                                                                                                                                                         
  main()                             
